### ISSUE TITLE
[Syntax] Template string parentheses have different highlighting than normal

### ISSUE THREAD

**Issue by Nevexo** [Nevexo/ecksClone#3]
![Example 2](https://awo.oooooooooooooo.ooo/i/m4w1.png)

Parentheses found within a template string (on JavaScript at least) show a different colour to when they're outside of a template string.

**Comment by Jack-JB** [comment]
inner-brackets fixed in 0be4ee60cab6bad6e53d560a939b57e04a7acb01

**Comment by Nevexo** [comment]
Resolved in e21c255
