### ISSUE TITLE
JS Light theme syntax issues

### ISSUE THREAD

**Issue by Nevexo** [Nevexo/ecksClone#9]
JavaScript highlighting issues (devel-light)

![image](https://user-images.githubusercontent.com/4786918/85213974-5b1a4480-b35d-11ea-9499-8e821f88a592.png)
The yellow item within arrays in JSON is too light compared to the editor background

Scopes: 
string.json
meta.structure.dictionary.json
meta.structure.dictionary.value.json
meta.structure.dictionary.json
source.json

**Comment by Jack-JB** [comment]
Resolved in **676e74f**
